# Practical Notebook

This is the practical notebook from our lectures. The idea is to maintain the pure state of our study notebook while we practicalize the codes on this environment.

In [1]:
import numpy as np
import pandas as pd

In [2]:
big_mart_sales = pd.read_csv("data/big_mart_sales_prediction.csv")
big_mart_sales.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [3]:
big_mart_sales.Item_Identifier.unique()

array(['FDA15', 'DRC01', 'FDN15', ..., 'NCF55', 'NCW30', 'NCW05'],
      dtype=object)

In [4]:
len(big_mart_sales.Item_Identifier.unique()), len(big_mart_sales)

(1559, 8523)

In [5]:
big_mart_sales.Item_Fat_Content.unique()

array(['Low Fat', 'Regular', 'low fat', 'LF', 'reg'], dtype=object)

In [6]:
big_mart_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            8523 non-null   object 
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object 
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object 
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object 
 7   Outlet_Establishment_Year  8523 non-null   int64  
 8   Outlet_Size                6113 non-null   object 
 9   Outlet_Location_Type       8523 non-null   object 
 10  Outlet_Type                8523 non-null   object 
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB


In [7]:
big_mart_sales.Item_Weight.fillna(big_mart_sales.Item_Weight.mean(), inplace=True)
big_mart_sales.Outlet_Size.ffill(inplace=True)

In [8]:
big_mart_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            8523 non-null   object 
 1   Item_Weight                8523 non-null   float64
 2   Item_Fat_Content           8523 non-null   object 
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object 
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object 
 7   Outlet_Establishment_Year  8523 non-null   int64  
 8   Outlet_Size                8523 non-null   object 
 9   Outlet_Location_Type       8523 non-null   object 
 10  Outlet_Type                8523 non-null   object 
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB


In [9]:
big_mart_sales.Item_Fat_Content.unique()

array(['Low Fat', 'Regular', 'low fat', 'LF', 'reg'], dtype=object)

In [10]:
big_mart_sales.Item_Fat_Content.replace({
    'low fat': 'Low Fat',
    'LF': 'Low Fat',
    'reg': 'Regular',
}, inplace=True)

In [11]:
big_mart_sales.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998      Medium               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [12]:
big_mart_sales.Item_Fat_Content.unique()

array(['Low Fat', 'Regular'], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder

In [14]:
categorical_columns = [
    'Item_Identifier', 'Item_Fat_Content', 'Item_Type', 
    'Outlet_Identifier', 'Outlet_Size', 'Outlet_Location_Type', 
    'Outlet_Type'
]

In [15]:
item_fat_content_encoder = OrdinalEncoder(categories=[['Low Fat', 'Regular']])

In [16]:
item_fat = big_mart_sales.Item_Fat_Content.to_numpy().reshape(-1, 1)

In [17]:
item_fat_content_encoder.fit(item_fat)

OrdinalEncoder(categories=[['Low Fat', 'Regular']])

In [18]:
item_fat_content_encoder.transform(item_fat)

array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [1.],
       [0.]])

In [19]:
item_fat_content_encoder.categories_

[array(['Low Fat', 'Regular'], dtype=object)]

In [20]:
item_identifier_encoder = LabelEncoder()

In [21]:
item_identifier = big_mart_sales.Item_Identifier.to_numpy().reshape(-1, 1)

In [22]:
item_identifier[:10]

array([['FDA15'],
       ['DRC01'],
       ['FDN15'],
       ['FDX07'],
       ['NCD19'],
       ['FDP36'],
       ['FDO10'],
       ['FDP10'],
       ['FDH17'],
       ['FDU28']], dtype=object)

In [23]:
item_identifier_encoder.fit(item_identifier)

C:\Users\ganiy\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LabelEncoder()

In [24]:
item_identifier_encoder.transform(item_identifier)

array([ 156,    8,  662, ..., 1357,  681,   50])

In [25]:
label_value = ['Item_Identifier', 'Item_Type']

In [26]:
big_mart_sales.Item_Type.unique(), len(big_mart_sales.Item_Type.unique())

(array(['Dairy', 'Soft Drinks', 'Meat', 'Fruits and Vegetables',
        'Household', 'Baking Goods', 'Snack Foods', 'Frozen Foods',
        'Breakfast', 'Health and Hygiene', 'Hard Drinks', 'Canned',
        'Breads', 'Starchy Foods', 'Others', 'Seafood'], dtype=object),
 16)

In [27]:
label_encoder = LabelEncoder()

In [28]:
label_encoder.fit_transform(big_mart_sales[label_value])

ValueError: y should be a 1d array, got an array of shape (8523, 2) instead.

Debugging the error
---

![Label Encoder Main Warning](images/label_encoder_main_warning.png)

I guess that's a fair point that needed to be started out! So basically the Label Encoders are meant to fit only one dimensional arrays. A possible fix to this though would be the code:

```python
big_mart_sales.loc[:, ['Item_Identifier', 'Item_Type']] = big_mart_sales[
    ['Item_Identifier', 'Item_Type']
].apply(LabelEncoder().fit_transform)
```

Which fits and transforms the features `Item_Identifier` and `Item_Type`. Learn more about the DataFrame apply method [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html).

In [29]:
item_fat_ohe = OneHotEncoder()

In [30]:
item_fat_content = big_mart_sales.Item_Fat_Content.to_numpy().reshape(-1, 1)

In [31]:
v = item_fat_ohe.fit_transform(item_fat_content)

In [32]:
v.toarray()

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [33]:
big_mart_sales.describe()

Item_Weight  Item_Visibility     Item_MRP  Outlet_Establishment_Year  \
count  8523.000000      8523.000000  8523.000000                8523.000000   
mean     12.857645         0.066132   140.992782                1997.831867   
std       4.226124         0.051598    62.275067                   8.371760   
min       4.555000         0.000000    31.290000                1985.000000   
25%       9.310000         0.026989    93.826500                1987.000000   
50%      12.857645         0.053931   143.012800                1999.000000   
75%      16.000000         0.094585   185.643700                2004.000000   
max      21.350000         0.328391   266.888400                2009.000000   

       Item_Outlet_Sales  
count        8523.000000  
mean         2181.288914  
std          1706.499616  
min            33.290000  
25%           834.247400  
50%          1794.331000  
75%          3101.296400  
max         13086.964800

In [34]:
max_value = 20
min_value = 5

In [35]:
min_value = min_value - 5
max_value = max_value - 5

In [36]:
min_value, max_value

(0, 15)

In [37]:
min_value/max_value, max_value/max_value

(0.0, 1.0)

In [38]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [39]:
scaler = StandardScaler()

In [40]:
item_mrp = big_mart_sales.Item_MRP.to_numpy().reshape(-1, 1)

In [41]:
big_mart_sales.Item_MRP = scaler.fit_transform(item_mrp)

In [42]:
big_mart_sales.Item_MRP.describe()

count    8.523000e+03
mean    -1.644427e-16
std      1.000059e+00
min     -1.761688e+00
25%     -7.574307e-01
50%      3.243893e-02
75%      7.170372e-01
max      2.021724e+00
Name: Item_MRP, dtype: float64