# Practical Notebook

This is the practical notebook from our lectures. The idea is to maintain the pure state of our study notebook while we practicalize the codes on this environment.

In [1]:
import numpy as np
import pandas as pd

In [2]:
loan_dataset = pd.read_csv("data/loan_prediction.csv", index_col='Loan_ID')
loan_dataset.head()

Gender Married Dependents     Education Self_Employed  \
Loan_ID                                                          
LP001002   Male      No          0      Graduate            No   
LP001003   Male     Yes          1      Graduate            No   
LP001005   Male     Yes          0      Graduate           Yes   
LP001006   Male     Yes          0  Not Graduate            No   
LP001008   Male      No          0      Graduate            No   

          ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
Loan_ID                                                                      
LP001002             5849                0.0         NaN             360.0   
LP001003             4583             1508.0       128.0             360.0   
LP001005             3000                0.0        66.0             360.0   
LP001006             2583             2358.0       120.0             360.0   
LP001008             6000                0.0       141.0             360.0   

          Credit_History Property_Area Loan_Status  
Loan_ID                                             
LP001002             1.0         Urban           Y  
LP001003             1.0         Rural           N  
LP001005             1.0         Urban           Y  
LP001006             1.0         Urban           Y  
LP001008             1.0         Urban           Y

In [3]:
from loan_prediction import prepare_dataset

In [4]:
prepare_dataset(loan_dataset)

In [5]:
loan_dataset.head()

Gender  Married  Dependents  Education  Self_Employed  \
Loan_ID                                                           
LP001002     1.0      0.0         0.0          0            0.0   
LP001003     1.0      1.0         1.0          0            0.0   
LP001005     1.0      1.0         0.0          0            1.0   
LP001006     1.0      1.0         0.0          1            0.0   
LP001008     1.0      0.0         0.0          0            0.0   

          ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
Loan_ID                                                                      
LP001002             5849                0.0  146.412162             360.0   
LP001003             4583             1508.0  128.000000             360.0   
LP001005             3000                0.0   66.000000             360.0   
LP001006             2583             2358.0  120.000000             360.0   
LP001008             6000                0.0  141.000000             360.0   

          Credit_History  Property_Area  Loan_Status  
Loan_ID                                               
LP001002             1.0              2            1  
LP001003             1.0              0            0  
LP001005             1.0              2            1  
LP001006             1.0              2            1  
LP001008             1.0              2            1

### Feature Selection making use of Feature Importance

In [6]:
loan_dataset.shape

(614, 12)

In [7]:
loan_dataset.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [8]:
target_column = "Loan_Status"

In [9]:
target = loan_dataset[target_column]
data = loan_dataset.drop(target_column, axis=1)

In [10]:
data.head()

Gender  Married  Dependents  Education  Self_Employed  \
Loan_ID                                                           
LP001002     1.0      0.0         0.0          0            0.0   
LP001003     1.0      1.0         1.0          0            0.0   
LP001005     1.0      1.0         0.0          0            1.0   
LP001006     1.0      1.0         0.0          1            0.0   
LP001008     1.0      0.0         0.0          0            0.0   

          ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
Loan_ID                                                                      
LP001002             5849                0.0  146.412162             360.0   
LP001003             4583             1508.0  128.000000             360.0   
LP001005             3000                0.0   66.000000             360.0   
LP001006             2583             2358.0  120.000000             360.0   
LP001008             6000                0.0  141.000000             360.0   

          Credit_History  Property_Area  
Loan_ID                                  
LP001002             1.0              2  
LP001003             1.0              0  
LP001005             1.0              2  
LP001006             1.0              2  
LP001008             1.0              2

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=.2, random_state=42, shuffle=True)
y_train.shape, y_test.shape

((491,), (123,))

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
rfc = RandomForestClassifier()

In [15]:
X_train.Married.ffill(inplace=True)

In [16]:
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [17]:
rfc.feature_importances_

array([0.02076993, 0.02545697, 0.04840157, 0.0252336 , 0.01862734,
       0.21274767, 0.11377898, 0.20214086, 0.05301536, 0.22878677,
       0.05104095])

In [18]:
for col, importance in zip(loan_dataset.columns, rfc.feature_importances_):
    print(col, importance * 100)

Gender 2.076992902996147
Married 2.545697159578203
Dependents 4.840156700333929
Education 2.5233600191666024
Self_Employed 1.862733554125602
ApplicantIncome 21.274766904629097
CoapplicantIncome 11.377897902215919
LoanAmount 20.214086331230824
Loan_Amount_Term 5.30153607359093
Credit_History 22.878677383381184
Property_Area 5.104095068751558


In [19]:
X_test.Married.ffill(inplace=True)

In [20]:
predictions = rfc.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
confusion_matrix(y_test, predictions)

array([[20, 23],
       [ 4, 76]], dtype=int64)

In [23]:
(20 + 75) / 123

0.7723577235772358

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
accuracy_score(y_test, predictions)

0.7804878048780488

In [26]:
dummy_result = np.ones((123,))

In [27]:
accuracy_score(y_test, dummy_result)

0.6504065040650406

In [28]:
dummy_result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [29]:
75 / (75 + 23)

0.7653061224489796

In [30]:
from sklearn.metrics import precision_score

In [31]:
precision_score(y_test, predictions)

0.7676767676767676

In [32]:
75 / 80

0.9375

In [33]:
from sklearn.metrics import recall_score

In [34]:
recall_score(y_test, predictions)

0.95

In [35]:
from sklearn.pipeline import Pipeline

In [36]:
loan_dataset = pd.read_csv("data/loan_prediction.csv", index_col='Loan_ID')
loan_dataset.head()

Gender Married Dependents     Education Self_Employed  \
Loan_ID                                                          
LP001002   Male      No          0      Graduate            No   
LP001003   Male     Yes          1      Graduate            No   
LP001005   Male     Yes          0      Graduate           Yes   
LP001006   Male     Yes          0  Not Graduate            No   
LP001008   Male      No          0      Graduate            No   

          ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
Loan_ID                                                                      
LP001002             5849                0.0         NaN             360.0   
LP001003             4583             1508.0       128.0             360.0   
LP001005             3000                0.0        66.0             360.0   
LP001006             2583             2358.0       120.0             360.0   
LP001008             6000                0.0       141.0             360.0   

          Credit_History Property_Area Loan_Status  
Loan_ID                                             
LP001002             1.0         Urban           Y  
LP001003             1.0         Rural           N  
LP001005             1.0         Urban           Y  
LP001006             1.0         Urban           Y  
LP001008             1.0         Urban           Y

In [37]:
target = loan_dataset[target_column]
data = loan_dataset.drop(target_column, axis=1)

In [38]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=.2, random_state=42, shuffle=True)
y_train.shape, y_test.shape

((491,), (123,))

In [39]:
X_train.head()

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
Loan_ID                                                                       
LP001273   Male     Yes          0  Graduate            No             6000   
LP001316   Male     Yes          0  Graduate            No             2958   
LP001758   Male     Yes          2  Graduate            No             6250   
LP002537   Male     Yes          0  Graduate            No             2083   
LP002493   Male      No          0  Graduate            No             4166   

          CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
Loan_ID                                                                     
LP001273             2250.0       265.0             360.0             NaN   
LP001316             2900.0       131.0             360.0             1.0   
LP001758             1695.0       210.0             360.0             1.0   
LP002537             3150.0       128.0             360.0             1.0   
LP002493                0.0        98.0             360.0             0.0   

         Property_Area  
Loan_ID                 
LP001273     Semiurban  
LP001316     Semiurban  
LP001758     Semiurban  
LP002537     Semiurban  
LP002493     Semiurban

In [40]:
drop_columns = ['Gender', 'Married']

continuous_columns = [
    'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount'
]

categorical_columns = [
    'Loan_Amount_Term', 'Dependents', 'Education', 
    'Self_Employed', 'Credit_History', 'Property_Area'
]

In [41]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder

In [42]:
cont_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

cat_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('scaler', OrdinalEncoder())
])

In [43]:
from sklearn.compose import ColumnTransformer

In [44]:
transformer = ColumnTransformer([
    ('drop_col', 'drop', drop_columns),
    ('cont', cont_pipe, continuous_columns),
    ('cat', cat_pipe, categorical_columns)
])

In [45]:
x = transformer.fit_transform(X_train)

In [48]:
X_test.iloc[1]

Gender                    Male
Married                    Yes
Dependents                   0
Education             Graduate
Self_Employed               No
ApplicantIncome           4310
CoapplicantIncome          0.0
LoanAmount               130.0
Loan_Amount_Term         360.0
Credit_History             NaN
Property_Area        Semiurban
Name: LP002223, dtype: object

In [49]:
y_test[1]

'Y'

In [50]:
import pickle

In [51]:
loan_predictor_model_pipeline = pickle.load(open('data/loan_predictor_model_pipeline.p', 'rb'))

In [52]:
type(loan_predictor_model_pipeline)

sklearn.pipeline.Pipeline